// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAknO3Bx2IPFXOP6pkcDWp0cErtelajK1c',
    appId: '1:1083276156656:web:380cb584ec1a0575a9ec35',
    messagingSenderId: '1083276156656',
    projectId: 'clotstore-1d7b3',
    authDomain: 'clotstore-1d7b3.firebaseapp.com',
    storageBucket: 'clotstore-1d7b3.firebasestorage.app',
    measurementId: 'G-1FSLVN8V44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXSRz5eIN4xmk1jIwYr9FIoge8cnPbnY',
    appId: '1:1083276156656:android:1629f173229dde7ca9ec35',
    messagingSenderId: '1083276156656',
    projectId: 'clotstore-1d7b3',
    storageBucket: 'clotstore-1d7b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACn8ts5NXGaavQ79RFHEOfmWXib3tHOQU',
    appId: '1:1083276156656:ios:a96590076fa0d1b1a9ec35',
    messagingSenderId: '1083276156656',
    projectId: 'clotstore-1d7b3',
    storageBucket: 'clotstore-1d7b3.firebasestorage.app',
    iosBundleId: 'com.example.clotStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACn8ts5NXGaavQ79RFHEOfmWXib3tHOQU',
    appId: '1:1083276156656:ios:a96590076fa0d1b1a9ec35',
    messagingSenderId: '1083276156656',
    projectId: 'clotstore-1d7b3',
    storageBucket: 'clotstore-1d7b3.firebasestorage.app',
    iosBundleId: 'com.example.clotStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAknO3Bx2IPFXOP6pkcDWp0cErtelajK1c',
    appId: '1:1083276156656:web:920ccd19907b4784a9ec35',
    messagingSenderId: '1083276156656',
    projectId: 'clotstore-1d7b3',
    authDomain: 'clotstore-1d7b3.firebaseapp.com',
    storageBucket: 'clotstore-1d7b3.firebasestorage.app',
    measurementId: 'G-2GF7X2R4GL',
  );
}
